version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: cejei_postgres
    environment:
      POSTGRES_DB: cejei_licencias
      POSTGRES_USER: cejei
      POSTGRES_PASSWORD: cejei
    ports:
      - "5532:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "cejei" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
